### ISSUE TITLE
Couldn't compile XML 3.99-0.5 on Windows

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-xml-feedstock#20]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

When fixing the CI in #19 so that XML 3.99-0.5 would be built for R 4.0 only, it failed to compile on Windows. It is able to compile [on the CRAN Windows servers](https://cran.r-project.org/web/checks/check_results_XML.html
), so it is theoretically possible. I'll willing to help troubleshoot if anyone can provide some clues as to what went wrong.

[Location of error in build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=251495&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=402)

Error message:

```
gcc -shared -s -o XML.dll tmp.def DocParse.o EventParse.o ExpatParse.o
HTMLParse.o NodeGC.o RSDTD.o RUtils.o Rcatalog.o Utils.o XMLEventParse.o
XMLHashTree.o XMLTree.o fixNS.o libxmlFeatures.o schema.o xmlsecurity.o
xpath.o -L/lib -lxml2 -liconv -lz -lws2_32
-LD:/bld/r-xml_1607806008211/_h_env/lib/R/bin/x64 -lR
NodeGC.o:NodeGC.c:(.rdata$.refptr.xmlFree[.refptr.xmlFree]+0x0):
undefined reference to `xmlFree'
XMLTree.o:XMLTree.c:(.rdata$.refptr.xmlStringTextNoenc[.refptr.xmlStringTextNoenc]+0x0):
undefined reference to `xmlStringTextNoenc'
xpath.o:xpath.c:(.rdata$.refptr.xmlMallocAtomic[.refptr.xmlMallocAtomic]+0x0):
undefined reference to `xmlMallocAtomic'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'XML'
```

**Comment by mbargull** [comment]
fixed via gh-33
